Web/221014/pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
   path('', views.index,name='index'),
   path('signup/', views.signup,name='signup'),
   path('login/', views.login,name='login'),
   path('logout/', views.logout,name='logout'),
   path('delete/<int:user_pk>', views.delete ,name='delete'),
   path('<int:user_pk>', views.profile ,name='profile'),
   path('profile/<str:username>', views.profile ,name='profile'),
   path('my_profile/', views.my_profile ,name='my_profile'),
   path('my_profile/edit/', views.edit_profile ,name='edit_profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/221014/pjt/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
   path('', views.index,name='index'),
   path('create/', views.create,name='create'),
   path('reviews/', views.reviews,name='reviews'),
   path('update/', views.update,name='update'),
   path('delete/<int:article_pk>', views.delete ,name='delete'),
   path('<int:user_pk>', views.index ,name='profile'),
   path('profile/', views.index ,name='personal_profile'),
   path('detail/<int:article_pk>', views.detail ,name='detail'),
   path('comments/<int:article_pk>/', views.comment_create, name='comment_create'),
   path('reviews_like/<int:article_pk>/', views.reviews_like, name='reviews_like'),
   path('main_like/<int:article_pk>/', views.main_like, name='main_like'),
]

Web/221014/pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/',include('articles.urls')),
    path('',include('main.urls') ),

    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Web/221014/pjt/templates/base.html
{% load static %}
{% load django_bootstrap5 %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
       </he<head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
        <!-- Bootstrap CSS v5.2.1 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
      
      </head>
<body>
  <nav class="navbar navbar-expand-lg bg-light d-flex align-items-center " style= "position:sticky; top:0px; left:0px; z-index: 1;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'accounts:index' %}">Movies</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item" >
            <a href="{% url 'articles:reviews' %}">reviews</a>
          </li>
        </ul>
          {% if user.is_authenticated %}
            <p class="login-comment" ><a href="{% url 'accounts:my_profile' %}">{{ user }}</a> 님 로그인 했음</p>
            <form action="{% url 'accounts:logout' %}" methon="POST">
              {% csrf_token %}
              <input type="submit" value = "logout">
            </form>  
          {% else %}
          <form action="{% url 'accounts:login' %}" methon="POST" class="d-flex">
            {% csrf_token %}
            <input type="submit" value = "login">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">signup</a>
          </form>
          
          {% endif %}
      </div>
    </div>
  </nav>
  <div class="container" style="margin-top:10px">
    {% block content %}
    
    {% endblock content %}
 </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</body>
</html>



<!doctype html>
<html lang="en">

<head>
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>

<body>
  <header>
    <!-- place navbar here -->
  </header>
  <main>

  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>