Web/장고/01-django-modelform-master/articles/urls.py
# URL설정을 app 단위로!
from django.urls import path 
from . import views

app_name = 'articles'

urlpatterns = [
  # http://127.0.0.1:8000/articles/
  path('', views.index, name='index'),
  # http://127.0.0.1:8000/articles/new/
  # path('new/', views.new, name='new'),
  # http://127.0.0.1:8000/articles/create/
  path('create/', views.create, name='create'),
  # http://127.0.0.1:8000/articles/1/ : 1번글
  # http://127.0.0.1:8000/articles/3/ : 3번글
  path('<int:pk>/', views.detail, name='detail'),
  # http://127.0.0.1:8000/articles/1/update/ : 1번글 수정
  # http://127.0.0.1:8000/articles/3/update/ : 3번글 수정
  path('<int:pk>/update/', views.update, name='update'),
]

Web/장고/01-django-modelform-master/articles/models.py
from django.db import models

# Create your models here.
'''
게시판 기능 
- 제목(20글자이내)
- 내용(긴 글)
- 글 작성시간/수정시간(자동으로 기록, 날짜/시간)
'''
# 1. 모델 설계 (DB 스키마 설계)
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Web/장고/01-django-modelform-master/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content']

Web/장고/01-django-modelform-master/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.

# 요청 정보를 받아서..
def index(request):
    # 게시글을 가져와서..
    articles = Article.objects.order_by('-pk')
    # Template에 전달한다. 
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

# def new(request):
#     article_form = ArticleForm()
#     context = {
#         'article_form': article_form
#     }
#     return render(request, 'articles/new.html', context=context)

def create(request):
    if request.method == 'POST':
        # DB에 저장하는 로직
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:index')
    else: 
        article_form = ArticleForm()
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/new.html', context=context)

def detail(request, pk):
    # 특정 글을 가져온다.
    article = Article.objects.get(pk=pk)
    # template에 객체 전달
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        # POST : input 값 가져와서, 검증하고, DB에 저장
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
            article_form.save()
            return redirect('articles:detail', article.pk)
        # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        article_form = ArticleForm(instance=article)
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/update.html', context)

Web/장고/01-django-modelform-master/articles/templates/articles/detail.html
<h1>{{ article.pk }}번 게시글</h1>
<p>{{ article.created_at }} | {{ article.updated_at }}</p>
<p>{{ article.content }} </p>
<a href="{% url 'articles:update' article.pk %}">수정하기</a>

Web/장고/01-django-modelform-master/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <h1>게시판</h1>
  <a href="{% url 'articles:create' %}">글 쓰기</a>
  {% for article in articles %}
  <h3><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></h3>
  <p>{{ article.created_at }} | {{ article.updated_at }}</p>
  <hr>
  {% endfor %}
</body>

</html>

Web/장고/01-django-modelform-master/articles/templates/articles/new.html
<h1>글쓰기</h1>

<!-- form : 사용자에게 양식을 제공하고 
  값을 받아서(input : name, value) 
  서버에 전송(form : action, method)-->
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  {{ article_form.as_p }}
  <!-- <label for="title">제목 : </label>
  <input type="text" name="title" id="title" required>
  <label for="content">내용 : </label>
  <textarea name="content" id="content" cols="30" rows="10" required></textarea> -->
  <input type="submit" value="글쓰기">
</form>

Web/장고/01-django-modelform-master/articles/templates/articles/update.html
<h1>글 수정하기</h1>

<form action="" method="POST">
  {% csrf_token %}
  {{ article_form.as_p }}
  <input type="submit" value="수정">
</form>