Web/장고/221006/pjt/movie/urls.py
from django.urls import path
from . import views


app_name = 'movie'

urlpatterns = [
    path('movie/',views.index,name='index'),
    path('create/',views.create,name='create'),
    path('delete/<int:pk>',views.delete,name='delete'),
    path('update/<int:pk>',views.update,name='update'),
]

Web/장고/221006/pjt/movie/models.py
from ipaddress import summarize_address_range
from django.db import models

# Create your models here.

class movie(models.Model):
    title = models.CharField(max_length=20)
    summary = models.TextField()
    running_time =  models.CharField(max_length=20)

Web/장고/221006/pjt/movie/forms.py
from socket import fromshare
from django import forms
from .models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = movie
        fields = [ 'title' , 'summary' , 'running_time' ]
        
    
    

Web/장고/221006/pjt/movie/views.py
from distutils.file_util import move_file
from django.shortcuts import render,redirect
from .models import movie
from .forms import MovieForm

# Create your views here.
app_name = "movie"

def index(request):

    movies = movie.objects.order_by('-pk')
    # Template에 전달한다. 
    print(len(movies))
    context = {
        'movies': movies
    }
    

    return render(request,'movie/index.html',context)


def create(request):
    if request.method == 'POST':
        # DB에 저장하는 로직
        movie_form = MovieForm(request.POST)
        if movie_form.is_valid():
            movie_form.save()
            print("save")
            return redirect('movie:index')
    else: 
        movie_form = MovieForm()
        print("else")
    context = {
        'movie_form': movie_form
    }
    return render(request, 'movie/new.html', context=context)
    

def delete(request,pk):

    print('hello')

    Movie = movie.objects.get(pk=pk)
    Movie.delete()

    return redirect('movie:index')


def update(request,pk):

    print('hello')

    Movie = movie.objects.get(pk=pk)
    Movie.delete()

    return redirect('movie:index')

Web/장고/221006/pjt/movie/templates/movie/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>영화 정보 제공 서비스</h1>
    <br>
    <a href="{% url 'movie:create' %}">글 쓰기</a>
    <table>
        <thead>
            <tr>
                <td>title</td>
                <td>review</td>
                <td>시간(분)</td>
                <td>삭제</td>
                <td>update</td>

            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
                <tr>
                    <td>{{movie.title}}</td>
                    <td>{{movie.summary}}</td>
                    <td>{{movie.running_time}}</td>
                    <td>
                        <a href="{% url 'movie:delete' movie.pk %}">del</a>
                    </td>
                    <td>
                        <a href="{% url 'movie:update' movie.pk %}">update</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</body>
</html>

Web/장고/221006/pjt/movie/templates/movie/new.html
<h1>글쓰기</h1>

<!-- form : 사용자에게 양식을 제공하고 
  값을 받아서(input : name, value) 
  서버에 전송(form : action, method)-->
<form action="{% url 'movie:create' %}" method="POST">
  {% csrf_token %}
  {{ movie_form.as_p }}
  <!-- <label for="title">제목 : </label>
  <input type="text" name="title" id="title" required>
  <label for="content">내용 : </label>
  <textarea name="content" id="content" cols="30" rows="10" required></textarea> -->
  <input type="submit" value="글쓰기">
</form>