Web/221108/pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    path('', views.index,name='index'),
    path('signup/', views.signup,name='signup'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('user_list/',views.user_list,name='user_list'),
    path('delete/<int:pk>', views.delete ,name='delete'),
#    path('<int:user_pk>', views.profile ,name='profile'),
    path('profile/<username>', views.profile ,name='profile'),
    path('edit_profile/<username>', views.edit_profile ,name='edit_profile'), 
    path('find_password/<int:stage>', views.find_password,name='find_password'),
#    path('my_profile/', views.my_profile ,name='my_profile'),
#    path('my_profile/edit/', views.edit_profile ,name='edit_profile'),
] 

Web/221108/pjt/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
#    path('', views.index,name='index'),
   path('create/', views.create,name='create'),
   path('edit/<int:pk>',views.edit,name='edit'),
   path('search/', views.search,name='search'),
#    path('reviews/', views.reviews,name='reviews'),
#    path('update/', views.update,name='update'),
#    path('delete/<int:article_pk>', views.delete ,name='delete'),
#    path('<int:user_pk>', views.index ,name='profile'),
#    path('profile/', views.index ,name='personal_profile'),
#    path('detail/<int:article_pk>', views.detail ,name='detail'),
#    path('comments/<int:article_pk>/', views.comment_create, name='comment_create'),
#    path('reviews_like/<int:article_pk>/', views.reviews_like, name='reviews_like'),
#    path('main_like/<int:article_pk>/', views.main_like, name='main_like'),
]

Web/221108/pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('items/',include('items.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/221108/pjt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
      h1{

        margin-top:10px;

      }

      ul {
        list-style:none;
      }
      
      nav {
        padding:5px;
      }

      nav li {
          float: left;
          padding-top:8px;
          padding-right:10px;
      }
      a{
        padding-top:7px;
        padding-left:10px;
        text-decoration: none;
        color:black;       
      }
      {{form.media}}   
    </style>


</head>
<body>
    
    <nav class="navbar-light bg-light d-flex justify-content-between " style="position: sticky; top: 0; z-index:1;" >
        <div class="d-flex">
          <a href="{% url 'accounts:index' %}">내일의 집</a>
          <ul>
            <li>
              <a  href="{% url 'accounts:index' %}">커뮤니티</a>
            </li>
            <li >
              <a  href="#">스토어</a>
            </li>
          </ul>
        </div>
        <form class="d-flex" method="POST" action="{% url 'articles:search' %}">
          {% csrf_token %}        
          <input class="form-control me-2" type="search" placeholder="검색어를 입력" name="search" >
          <button class="btn btn-outline-success" type="submit" style="width:100px;">검색 </button>
        </form>


        <div class=' d-flex justify-content-center align-itmes-center ' style="margin:5px; margin-right:10px; margin-top:1px; ">
          {% if user.is_authenticated %}
            <p style="" ><a href="{% url 'accounts:profile' user.username %}" >{{ user }}</a>님 로그인 했음</p>
            <a href="{% url 'accounts:logout'%}">logout</a>
          {% else %}
            <a href="{% url 'accounts:login'%}" style='margin-right:5px;'>login</a>
            <a href="{% url 'accounts:signup'%}">signup</a>
          {% endif %}
        </div>
      </nav>
    <div class="container d-flex flex-column justify-content-center align-items-center">     
          {% block content %}
          {% endblock %} 
    </div>

    <footer style="width:100%; height:150px; background-color:black; display: flex; justify-content:center; align-items:center;">
    
        <p style="color:white">
          footer
        </p>


    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>